name: heartbeat
on:
  schedule:
    - cron: "0 2 1 * *"
  workflow_dispatch:

jobs:
  heartbeat:
    name: heartbeat
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.NFLVERSE_GH_TOKEN }}
      GITHUB_PAT: ${{ secrets.NFLVERSE_GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'hearbeat'
      - name: Commit heartbeat
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          date > .heartbeat
          git add .heartbeat
          git commit -m "Keep GHA alive `date`" || echo "No changes to commit"
          git push || echo "No changes to commit"
