# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:
    inputs:
      full_rebuild:
        description: 'Full Rebuild'
        required: true
        default: false
        type: boolean

name: Update FTN Data

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-22.04,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.NFLVERSE_GH_TOKEN }}
      FULL_REBUILD: ${{ inputs.full_rebuild || false }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Run FTN participation script
        run: |
          if [ $FULL_REBUILD == true ]
          then
            Rscript exec/update_pbp_participation.R "ALL YEARS"
          else
            Rscript exec/update_pbp_participation.R
          fi
