# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
    # every six hours
    - cron: '0 */6 * 9-12,1-2 *'
  workflow_dispatch:

name: Update FTN Data

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-22.04,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.NFLVERSE_GH_TOKEN }}
      FTN_API_KEY: ${{ secrets.FTN_API_KEY }}
      FTN_NFLVERSE_ENDPOINT: ${{ secrets.FTN_NFLVERSE_ENDPOINT }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Run FTN update script
        run: Rscript exec/update_ftn.R
