# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:
    inputs:
      season_rebuild:
        description: 'Rebuild Season (9999 defaults to latest season). Do multiple seasons comma separated, e.g. 2017,2019,2021'
        required: false
        default: 9999
        type: number
      full_rebuild:
        description: 'Full Rebuild (overwrites above season)'
        required: true
        default: false
        type: boolean

name: Update FTN Participation

jobs:
  setup:
    runs-on: ubuntu-latest
    name: setup
    env:
      GH_TOKEN: ${{ secrets.NFLVERSE_GH_TOKEN }}
      FULL_REBUILD: ${{ inputs.full_rebuild || false }}
      SEASON_REBUILD: ${{ inputs.season_rebuild || 9999 }}
    outputs:
      seasons: ${{ steps.query_seasons.outputs.seasons }}
    steps:
      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: nflverse/nflverse-workflows

      - id: query_seasons
        name: Query Seasons
        run: |
          if [ $FULL_REBUILD == true ]
          then
            seasons=$( Rscript -e 'nflverse.workflows::get_season_range(2023)' )
          elif [ $SEASON_REBUILD == 9999 ]
          then
            seasons=$( Rscript -e 'nflverse.workflows::get_current_season()' )
          else
            seasons="[$SEASON_REBUILD]"
          fi
          echo "seasons=$seasons" >> "$GITHUB_OUTPUT"

  update_ftn_partcipation:
    needs: setup
    name: Update ${{ matrix.season }} ${{ matrix.type }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        season: ${{ fromJson(needs.setup.outputs.seasons) }}
        type: ["participation"]
    env:
      GH_TOKEN: ${{ secrets.NFLVERSE_GH_TOKEN }}
      NFLVERSE_UPDATE_SEASON: ${{ matrix.season }}
      NFLVERSE_UPDATE_TYPE: ${{ matrix.type }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          extra-repositories: 'https://nflverse.r-universe.dev'
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: nflverse/nflverse-data,
      - name: Release ${{ matrix.type }}
        run: Rscript exec/update_ftn_participation.R
